language: node_js
node_js:
  - 13
services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./project3-Refactor-Monolith-to-Microservices-and-Deploy/udagram-api-feed
  - docker build -t udagram-api-user ./project3-Refactor-Monolith-to-Microservices-and-Deploy/udagram-api-user
  - docker build -t udagram-frontend ./project3-Refactor-Monolith-to-Microservices-and-Deploy/udagram-frontend
  - docker build -t reverseproxy ./project3-Refactor-Monolith-to-Microservices-and-Deploy/udagram-reverseproxy
  #tagging
  - docker tag udagram-api-feed huyvd94/udagram-api-feed:v1
  - docker tag udagram-api-user huyvd94/udagram-api-user:v1
  - docker tag udagram-frontend huyvd94/udagram-frontend:v2
  - docker tag reverseproxy huyvd94/reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push huyvd94/udagram-api-feed:v1
  - docker push huyvd94/udagram-api-user:v1
  - docker push huyvd94/udagram-frontend:v2
  - docker push huyvd94/reverseproxy:v1
